### ISSUE TITLE
A user shall be able to register as a teacher.

### ISSUE THREAD

**Issue by DeveloperSpoot** [codyseibert/online-classroom#1]
The idea for this story is after the user logs in, redirect them to a role selection page that looks like this

![image](https://user-images.githubusercontent.com/1868782/180570265-d072e48c-e6d5-445e-bc73-a14aacf3630a.png)

after the user clicks on the teacher role, update their user.role property using prisma and setup a next-auth callback to set the role on the session

### Tasks

- [x] create a page where a user can select a role (@MohammedBakr44)
- [x] redirect the user to this "select a role" page if the user's role is not set
- [x] setup next-auth to attach a role to the session (@codyseibert)
- [x] add an endpoint to set the user's role as teacher after clicking the "I'm a Teacher" in the UI
  - [x] this endpoint should throw an error if a role is already selected for the user (don't want people switching roles once created)
- [x] update the User's model in Prisma.schema to allow us setting a role in the database (@codyseibert)
- [x] redirect the user to a dashboard page that says HELLO TEACHER if the user's role is `teacher`
