### ISSUE TITLE
A teacher shall be able to create a course.

### ISSUE THREAD

**Issue by DeveloperSpoot** [codyseibert/online-classroom#2]
As a teacher, I should be able to create a new course which I can describe and name, and also provide an enroll period, start date and ends date.

![Image](https://user-images.githubusercontent.com/1868782/182031501-c987463e-2886-4979-84c0-322c11a44e48.png)

## Tasks

- [ ] update teacher-wizard.tsx to look like the design - **Assigned to fredrikjohanssonnn**
- [ ] validate that all fields are entered - **Assigned to fredrikjohanssonnn**
- [ ] validate the enrollment end date is after the enrollment start date - **Assigned to fredrikjohanssonnn**
- [ ] validate the course end date is after the course start date - **Assigned to fredrikjohanssonnn**
- [ ] use a rich text editor for the description
- [ ] setup prisma model for course
- [ ] run prisma migrate dev
- [ ] add trpc endpoint for created a new course
- [ ] require a teacher role to create a course
